name: CI Tests

on:
  push:
    branches: [ "**" ] # Adjust as needed

jobs:
  test-frontened:
    name: "Test Frontend"
    uses: ./.github/workflows/test-frontend.yml

  test-backend:
    name: "Test Backend"
    uses: ./.github/workflows/test-backend.yml
