---
name: CI Pipeline name

on:
    push:
      branches:
        - '**'
    pull_request:
      branches:
        - '**'

jobs:
  front_test:
    name: Frontend Test
    runs-on: ubuntu-latest

    env:
        VARIABLE_ONE: value_one
    steps:
      - uses: actions/checkout@v4

      - name: Echo variables
        run: |
            echo "NEW_VARIABLE=NEW_VARIABLE_VALUE" >> $GITHUB_ENV
            export PRIVATE_VARIABLE=PRIVATE_VARIABLE_VALUE

            # This works
            echo $VARIABLE_ONE 

            # This does not work
            echo $NEW_VARIABLE 
            
            # This works
            echo $PRIVATE_VARIABLE 
            cat source_code.txt

      - name: Echo previous variables
        run: |
            echo $VARIABLE_ONE
            echo $NEW_VARIABLE
            echo $PRIVATE_VARIABLE
            cat source_code.txt