name: Manual Build

on:
  workflow_dispatch:
    inputs:
      build_rpm:
        description: "Build RPM?"
        required: true
        default: "false"
      build_exe:
        description: "Build EXE?"
        required: true
        default: "false"
      build_deb:
        description: "Build DEB?"
        required: true
        default: "false"
      build_docker:
        description: "Build Docker image?"
        required: true
        default: "false"

jobs:
  package-war:
    name: "package-war"
    uses: ./.github/workflows/package-war.yml

  package-deb:
    name: "package-deb"
    needs: package-war
    uses: ./.github/workflows/package-deb.yml
    if: ${{ github.event.inputs.build_deb == 'true' }}

  package-rpm:
    name: "package-rpm"
    needs: package-war
    if: ${{ github.event.inputs.build_rpm == 'true' }}
    uses: ./.github/workflows/package-rpm.yml

  package-exe:
    name: "package-exe"
    needs: package-war
    if: ${{ github.event.inputs.build_exe == 'true' }}
    uses: ./.github/workflows/package-exe.yml


  package-docker:
    name: "package-docker"
    needs: package-war
    uses: ./.github/workflows/package-docker.yml
    if: ${{ github.event.inputs.build_docker == 'true' }}

