name: Release Build

on:
  push:
    tags:
      - '*Beta'
      - '*beta'
      - '*Final'
      - '*final'

jobs:
  package-war:
    name: "package-war"
    uses: ./.github/workflows/package-war.yml


  package-deb:
    name: "package-deb"
    needs: package-war
    uses: ./.github/workflows/package-deb.yml


  package-rpm:
    name: "package-rpm"
    needs: package-war
    uses: ./.github/workflows/package-rpm.yml


  package-exe:
    name: "package-exe"
    needs: package-war
    uses: ./.github/workflows/package-exe.yml


  package-docker:
    name: "package-docker"
    needs: package-war
    uses: ./.github/workflows/package-docker.yml

