name: Test Frontend

on:
  workflow_call:

jobs:
  test-frontend:
    name: "Test Frontend"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Testing Frontend
        run: |
            echo "Testing Frontend"
