name: Test Backend

on:
  workflow_call:

jobs:
  test-backend:
    name: "Test Backend"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Testing Backend
        run: |
            echo "Testing Backend"
