name: Test Backend

on:
  workflow_call:
    secrets:
      GITHUB_TOKEN:
        description: 'GITHUB_TOKEN'
        required: true

jobs:
  test-backend:
    name: "Test Backend"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Testing Backend
        run: |
            echo "Testing Backend"
