name: Test Frontend

on:
  workflow_call:
    secrets:
      GITHUB_TOKEN:
        description: 'GITHUB_TOKEN'
        required: true

jobs:
  test-frontend:
    name: "Test Frontend"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Testing Frontend
        run: |
            echo "Testing Frontend"
